import type { Metadata } from "next";
import "./globals.css";
import { Frame } from "@/components/layout/frame";
import { cn } from "@/utils/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", "font-sans")}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <Frame>{children}</Frame>
      </body>
    </html>
  );
}
