// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from "node:fs";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Local dev keeps secrets in .env; the deploy box keeps them in .env.production.
if (existsSync(".env")) {
  config({ path: ".env" });
} else if (existsSync(".env.production")) {
  config({ path: ".env.production" });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
